# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - goerr113
    - funlen
    - gocyclo
    - cyclop
    - gocognit
    - musttag
    - lll
    - maligned
    - gochecknoglobals
    - gomnd
    - wrapcheck
    - paralleltest
    - forbidigo
    - exhaustivestruct
    - interfacer # deprecated
    - forcetypeassert
    - scopelint # deprecated
    - ifshort # too many false positives
    - golint # deprecated
    - varnamelen
    - tagliatelle
    - errname
    - ireturn
    - exhaustruct
    - nonamedreturns
    - nosnakecase
    - structcheck
    - varcheck
    - deadcode
    - testableexamples
    - dupword
    - depguard
    - tagalign

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - gomnd
        - goconst
        - goerr113
        - noctx
        - funlen
        - dupl
        - structcheck
        - unused
        - unparam
        - nosnakecase
      path: "_test.go"
    - linters:
        - errcheck # Error checking omitted for brevity.
        - gosec
      path: "example_"
    - linters:
        - staticcheck
      text: "SA1019: strings.Title .+ deprecated"

