# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  misspell:
    locale: US
  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - nilnil
    - err113
    - funlen
    - gocyclo
    - cyclop
    - gocognit
    - musttag
    - intrange
    - copyloopvar
    - lll
    - gochecknoglobals
    - wrapcheck
    - paralleltest
    - forbidigo
    - forcetypeassert
    - varnamelen
    - tagliatelle
    - errname
    - ireturn
    - exhaustruct
    - nonamedreturns
    - testableexamples
    - dupword
    - depguard
    - tagalign
    - mnd
    - testifylint
    - recvcheck

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019: strings.Title .+ deprecated"

    - linters:
        - mnd
        - goconst
        - noctx
        - funlen
        - dupl
        - unused
        - unparam
      path: "_test.go"
    - linters:
        - errcheck # Error checking omitted for brevity.
        - gosec
      path: "example_"
    - linters:
        - revive
      text: "unused-parameter: parameter"

