name: test
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
env:
  GO111MODULE: "on"
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.11.x, 1.12.x, 1.13.x, 1.14.x]
    runs-on: ubuntu-latest
    steps:
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: checkout code
        uses: actions/checkout@v2
      - name: test
        run: go test -v -cover -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: code coverage
        uses: codecov/codecov-action@v1